Radius: 100
GraceTime: 3
GameTime: 60
messages:
  Prefix: '&f[&3WinTag&f] '
  YouAreIt: '&aYou are it!'
  SomeoneIsIt: '&a{player} is it!'
  GameStart: '&a{player} started a game of tag!'
  GameStop: '&aGame over. {player} lost.'
  YouLost: '&aYou lost the game!'
  AlreadyRunning: '&cA game is already running!'
  NoGameRunning: '&cThere is no game running!'
  ConfigReloaded: '&aThe configuration has been reloaded.'